### ISSUE TITLE
mapton-base build error

### ISSUE THREAD

**Issue by ghasem110** [trixon/mapton#53]
Failed to execute goal org.apache.netbeans.utilities:nbm-maven-plugin:4.6:manifest (default-manifest) on project mapton-base: Uncategorized problems with NetBeans dependency verification (maybe MNBMODULE-102 or wrong maven dependency metadata). Supposedly external classes are used in the project's binaries but the classes are not found on classpath. Class usages: [java.lang.Module] -> [Help 1]

**Comment by trixon** [comment]
@ghasem110 It looks like you cut off some interesting information but my guess would be that your JDK is missing JavaFX.
Have a look at https://github.com/trixon/mapton#building-mapton and see how that works for you.

**Comment by ghasem110** [comment]
thank's patrik..
it's ok but when build another error occured....

------------------------------------------------------------------------
Reactor Summary for mapton-parent 2.2.0:

mapton-parent ...................................... SUCCESS [  0.149 s]
mapton-branding .................................... SUCCESS [  1.200 s]
mapton-api ......................................... SUCCESS [  4.008 s]
mapton-base ........................................ SUCCESS [  1.121 s]
core ............................................... SUCCESS [  1.105 s]
google-maps ........................................ SUCCESS [  1.147 s]
maintenance ........................................ SUCCESS [  0.978 s]
me-gmapsfx ......................................... SUCCESS [  0.965 s]
me-jxmapviewer2 .................................... SUCCESS [  0.930 s]
me-worldwind ....................................... SUCCESS [  3.443 s]
me-mapjfx .......................................... FAILURE [  0.495 s]
poi-bookmarks ...................................... SKIPPED
POI Trv Traffic Information ........................ SKIPPED
se-bookmarks ....................................... SKIPPED
se-geonames ........................................ SKIPPED
se-google .......................................... SKIPPED
se-nominatim ....................................... SKIPPED
se-poi ............................................. SKIPPED
te-swetrans ........................................ SKIPPED
WMS EOX ............................................ SKIPPED
WMS Bing ........................................... SKIPPED
WMS Lantmäteriet ................................... SKIPPED
WMS NASA ........................................... SKIPPED
Editors ............................................ SKIPPED
POI WorldWind ...................................... SKIPPED
Reports ............................................ SKIPPED
Base64 ............................................. SKIPPED
Files .............................................. SKIPPED
GeoNames Visualizer ................................ SKIPPED
Notes .............................................. SKIPPED
Photos ............................................. SKIPPED
XKCD ............................................... SKIPPED
Wikipedia .......................................... SKIPPED
Wikipedia WorldWind ................................ SKIPPED
Seasonal ........................................... SKIPPED
application ........................................ SKIPPED
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time:  16.105 s
Finished at: 2021-04-24T14:41:08+04:30
------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/conf/logging/
constituent[1]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/org.eclipse.sisu.inject-0.3.4.jar
constituent[2]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-resolver-impl-1.4.1.jar
constituent[3]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/commons-io-2.5.jar
constituent[4]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/plexus-cipher-1.7.jar
constituent[5]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/guava-25.1-android.jar
constituent[6]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-artifact-3.6.3.jar
constituent[7]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-settings-builder-3.6.3.jar
constituent[8]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/org.eclipse.sisu.plexus-0.3.4.jar
constituent[9]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-shared-utils-3.2.1.jar
constituent[10]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/guice-4.2.1-no_aop.jar
constituent[11]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/plexus-utils-3.2.1.jar
constituent[12]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-resolver-transport-wagon-1.4.1.jar
constituent[13]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/plexus-sec-dispatcher-1.4.jar
constituent[14]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/wagon-file-3.3.4.jar
constituent[15]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/cdi-api-1.0.jar
constituent[16]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-builder-support-3.6.3.jar
constituent[17]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-repository-metadata-3.6.3.jar
constituent[18]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/javax.inject-1.jar
constituent[19]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/jcl-over-slf4j-1.7.29.jar
constituent[20]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/commons-cli-1.4.jar
constituent[21]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-settings-3.6.3.jar
constituent[22]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-compat-3.6.3.jar
constituent[23]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-embedder-3.6.3.jar
constituent[24]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-model-3.6.3.jar
constituent[25]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/jsoup-1.12.1.jar
constituent[26]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-resolver-api-1.4.1.jar
constituent[27]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/jansi-1.17.1.jar
constituent[28]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-resolver-util-1.4.1.jar
constituent[29]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-resolver-provider-3.6.3.jar
constituent[30]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-plugin-api-3.6.3.jar
constituent[31]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/jsr250-api-1.0.jar
constituent[32]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/slf4j-api-1.7.29.jar
constituent[33]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-resolver-spi-1.4.1.jar
constituent[34]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/commons-lang3-3.8.1.jar
constituent[35]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-core-3.6.3.jar
constituent[36]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-model-builder-3.6.3.jar
constituent[37]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/wagon-provider-api-3.3.4.jar
constituent[38]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/plexus-component-annotations-2.1.0.jar
constituent[39]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/plexus-interpolation-1.25.jar
constituent[40]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/wagon-http-3.3.4-shaded.jar
constituent[41]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-slf4j-provider-3.6.3.jar
constituent[42]: file:/home/ghkh/bin/netbeans-12.3/netbeans/java/maven/lib/maven-resolver-connector-basic-1.4.1.jar
---------------------------------------------------
Exception in thread "main" java.lang.AssertionError
	at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
	at jdk.compiler/com.sun.tools.javac.util.Assert.check(Assert.java:46)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:247)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.readSourceFile(JavaCompiler.java:837)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ImplicitCompleter.complete(JavacProcessingEnvironment.java:1530)
	at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:642)
	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1326)
	at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.complete(Type.java:1140)
	at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.getTypeArguments(Type.java:1066)
	at jdk.compiler/com.sun.tools.javac.code.Printer.visitClassType(Printer.java:237)
	at jdk.compiler/com.sun.tools.javac.code.Printer.visitClassType(Printer.java:52)
	at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.accept(Type.java:993)
	at jdk.compiler/com.sun.tools.javac.code.Printer.visit(Printer.java:136)
	at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument(AbstractDiagnosticFormatter.java:199)
	at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments(AbstractDiagnosticFormatter.java:167)
	at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:111)
	at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:67)
	at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument(AbstractDiagnosticFormatter.java:185)
	at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments(AbstractDiagnosticFormatter.java:167)
	at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:111)
	at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:67)
	at jdk.compiler/com.sun.tools.javac.util.JCDiagnostic.getMessage(JCDiagnostic.java:788)
	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$DiagnosticSourceUnwrapper.getMessage(ClientCodeWrapper.java:799)
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:131)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

**Comment by trixon** [comment]
I really can't tell from that,
try to build 2.2.1-SNAPSHOT from develop instead.
Note the updated build instructions.

**Comment by ghasem110** [comment]
thank you patrik... i fix it...
