### ISSUE TITLE
Fails to show WorldWind tab on M1 Mac

### ISSUE THREAD

**Issue by tmulle** [trixon/mapton#59]
When starting up the application the Map tab is empty and an exception appears in the IDE.
```java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/hh/zxltvdg95x57jm4ln9b7wl380000gn/T/jogamp_0000/file_cache/jln17053077215352618443/jln3565888158427884381/natives/macosx-universal/libgluegen_rt.dylib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:604)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
	at com.jogamp.common.os.Platform$1.run(Platform.java:321)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
	at com.jogamp.opengl.GLProfile.<clinit>(GLProfile.java:154)
	at gov.nasa.worldwind.Configuration.getMaxCompatibleGLProfile(Configuration.java:658)
	at gov.nasa.worldwind.Configuration.getRequiredGLCapabilities(Configuration.java:671)
	at gov.nasa.worldwind.awt.WorldWindowGLJPanel.<init>(WorldWindowGLJPanel.java:63)
	at org.mapton.worldwind.WorldWindowPanel.<init>(WorldWindowPanel.java:108)
	at org.mapton.worldwind.WorldWindMapEngine.init(WorldWindMapEngine.java:318)
	at org.mapton.worldwind.WorldWindMapEngine.lambda$create$1(WorldWindMapEngine.java:128)
[catch] at java.base/java.lang.Thread.run(Thread.java:833)
```

This is because there are no libs for M1 ARM for the WorldWind libs in the download.

**Comment by trixon** [comment]
Thanks @tmulle for reporting and confirming what I suspected. I have not had a decent mac in years so I'm not sure how Mapton behaves even on a classic CPU.

Hopefully the WorldWind team will fix this, I noticed your report there too.

Note that I'm not using the official version instead I use https://github.com/pcmehlitz/WorldWindJava-pcm by @pcmehlitz.
